# Generated by Django 4.0.3 on 2022-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
