# Generated by Django 4.0.3 on 2022-04-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_bigcategoryname_bigcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigcategory',
            options={'verbose_name_plural': 'Big Categories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
