# Generated by Django 4.0.4 on 2022-04-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigcategory',
            name='menwomen',
        ),
        migrations.AddField(
            model_name='product',
            name='menwomen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.menwomen'),
        ),
    ]
