# Generated by Django 4.0.4 on 2022-04-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_bigcategory_menwomen_product_menwomen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenWomen',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='menwomen',
            new_name='gender',
        ),
    ]
