# Generated by Django 4.0.4 on 2022-05-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_menwomen_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Primaryimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
