# Generated by Django 4.0.4 on 2022-05-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_primaryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('size', models.CharField(max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
