# Generated by Django 4.0.4 on 2022-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_quantity_remove_product_size_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test product'),
            preserve_default=False,
        ),
    ]
