# Generated by Django 4.0.4 on 2022-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Secondimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
