# Generated by Django 4.0.4 on 2022-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_secondimage_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Thirdimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
