# Generated by Django 4.0.4 on 2022-05-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='warrantyStatus',
            field=models.CharField(default='', max_length=200),
        ),
    ]
