# Generated by Django 4.0.4 on 2022-05-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_distributor_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
