# Generated by Django 4.0.4 on 2022-05-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_secondimage_alter_product_thirdimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
