# Generated by Django 4.0.4 on 2022-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_order_mobile_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
