# Generated by Django 4.0.4 on 2022-05-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
