# Generated by Django 4.0.4 on 2022-05-08 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_reviewitem_reviewlist_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
