# Generated by Django 4.0.4 on 2022-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_reviewitem_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
