# Generated by Django 4.0.4 on 2022-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_order_customer_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
