# Generated by Django 4.0.4 on 2022-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_reviewitem_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='review_status',
            field=models.CharField(blank=True, choices=[('Not Approved', 'Not Approved'), ('Approved', 'Approved')], max_length=50, null=True),
        ),
    ]
