# Generated by Django 4.0.4 on 2022-05-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_productmanagersadmin_alter_product_secondimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productmanagersadmin',
            name='mobile',
        ),
        migrations.AddField(
            model_name='productmanagersadmin',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.distributor'),
        ),
    ]
