# Generated by Django 4.0.4 on 2022-05-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_alter_product_primaryimage_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_completed',
            new_name='delivery_completed',
        ),
    ]
