# Generated by Django 4.0.4 on 2022-05-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_order_distributor_reviewitem_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='distributor',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.distributor'),
        ),
    ]
