# Generated by Django 4.0.3 on 2022-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_order_refund_granted_order_refund_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order in transit', 'Order in transit'), ('Order delivered', 'Order Delivered')], max_length=50, null=True),
        ),
    ]
