# Generated by Django 4.0.3 on 2022-05-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
