# Generated by Django 4.0.4 on 2022-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_wishlist_wishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='others',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
