# Generated by Django 4.0.4 on 2022-05-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_category_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='others',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order in transit', 'Order in transit'), ('Order delivered', 'Order Delivered'), ('Order cancelled', 'Order cancelled'), ('Order returned', 'Order returned')], max_length=50, null=True),
        ),
    ]
