# Generated by Django 4.0.4 on 2022-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_remove_order_subtotal_cart_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order In transit', 'Order In Transit'), ('Order Delivered', 'Order Delivered'), ('Order Cancelled', 'Order Cancelled'), ('Order Returned', 'Order Returned')], max_length=50, null=True),
        ),
    ]
