# Generated by Django 4.0.4 on 2022-06-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_alter_orderproduct_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanagersadmin',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.distributor'),
        ),
    ]
