# Generated by Django 4.0.4 on 2022-06-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_salesmanagersadmin_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
