# Generated by Django 4.0.4 on 2022-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_order_intransit_order_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order In Transit', 'Order In Transit'), ('Order Delivered', 'Order Delivered'), ('Order Cancelled', 'Order Cancelled'), ('Order Returned', 'Order Returned')], max_length=50, null=True),
        ),
    ]
