# Generated by Django 4.0.4 on 2022-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_alter_orderproduct_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
