# Generated by Django 4.0.4 on 2022-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
